### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ShadowManu** [ShadowManu/diogenes#1]
For creating a prototype clone of a certain oldie RTS game (not mentioned for copyright), here is a description of tasks that must be worked on, in order to have a proper game.

UNIT AND GROUP MOVEMENT, BEHAVIOR AND PROPERTIES
- [ ] Unit data structure (@daralion)
- [ ] Unit Select & Move (@daralion)
- [ ] Unit attack (@daralion)
- [ ] Resource Gathering
- [ ] Entity Building
- [ ] Waypoint movement
- [ ] Group Unit Movement
- [ ] Group Unit Formation
- [ ] Setting Patrols
- [ ] Setting Stance

MAP & MAP GEN
- [ ] Tile Data Structure (@ShadowManu)
- [ ] Map Data Structure (@ShadowManu)
- [ ] Entity Data Structure
   - [ ] Buildings
   - [ ] Resources
   - [ ] Decorations
- [ ] Entity placement
- [ ] Map Editor
- [ ] Map Generation

TECH
- [ ] Modifiers Data Structures
- [ ] Tech Data Structure
- [ ] Tech tree Data Structure

PLAYER
- [ ] Player Structure

UI/UX
- [ ] Visualizer
- [ ] Shortcuts
- [ ] Building Visualizer
- [ ] Units Visualizer
- [ ] Resources Header
- [ ] MiniMap
- [ ] MiniMap Filters
- [ ] Vfx/Sfx

NETWORK
- (Requires investigation)

AI
- (Pending)
